/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VaccineRegistrationSystem;

import Classes.Appointment;
import Classes.User;
import java.io.FileWriter;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Asus
 */
public class PeopleVaccineRegistration extends javax.swing.JFrame {
        User user = new User();
        Appointment a = new Appointment();
    
    /**
     * Creates new form PeopleVaccineResgistration
     */
    public PeopleVaccineRegistration() {
        initComponents();
        lblName.setText(user.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        lblClose2 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        btnCancelApp = new javax.swing.JButton();
        btnRegister = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        lblVacStatus = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblIC1 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        lblCentre = new javax.swing.JLabel();
        lblSlot = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        lblVaccine = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel8.setBackground(new java.awt.Color(0, 0, 0));

        jLabel16.setFont(new java.awt.Font("Cambria Math", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Vaccine Registration");

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/vaccine.png"))); // NOI18N
        jLabel17.setText("jLabel13");

        lblClose2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-close-window-30.png"))); // NOI18N
        lblClose2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblClose2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblClose2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(369, 369, 369)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblClose2)
                .addGap(35, 35, 35))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(lblClose2))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(jLabel16))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel9.setBackground(new java.awt.Color(204, 204, 255));

        jLabel4.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        jLabel4.setText("Vaccination Status");

        jLabel6.setFont(new java.awt.Font("Cambria Math", 1, 16)); // NOI18N
        jLabel6.setText("Centre:");

        jLabel18.setFont(new java.awt.Font("Cambria Math", 1, 16)); // NOI18N
        jLabel18.setText("Vaccination Status:");

        jLabel19.setFont(new java.awt.Font("Cambria Math", 1, 16)); // NOI18N
        jLabel19.setText("Slot:");

        btnCancelApp.setBackground(new java.awt.Color(255, 204, 204));
        btnCancelApp.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        btnCancelApp.setText("Cancel Appointment");
        btnCancelApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelAppActionPerformed(evt);
            }
        });

        btnRegister.setBackground(new java.awt.Color(204, 255, 255));
        btnRegister.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        jLabel7.setText("Registered People Details");

        jLabel22.setFont(new java.awt.Font("Cambria Math", 1, 16)); // NOI18N
        jLabel22.setText("Name: ");

        lblVacStatus.setFont(new java.awt.Font("Cambria Math", 0, 16)); // NOI18N
        lblVacStatus.setForeground(new java.awt.Color(51, 51, 255));
        lblVacStatus.setText("Not Registered");

        lblName.setFont(new java.awt.Font("Cambria Math", 0, 16)); // NOI18N
        lblName.setText("lbl");
        lblName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lblNameKeyReleased(evt);
            }
        });

        lblIC1.setFont(new java.awt.Font("Cambria Math", 0, 16)); // NOI18N
        lblIC1.setText("lbl");
        lblIC1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lblIC1KeyReleased(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Cambria Math", 1, 16)); // NOI18N
        jLabel23.setText("IC/ Passport No: ");

        lblCentre.setFont(new java.awt.Font("Cambria Math", 0, 16)); // NOI18N
        lblCentre.setText("lblCentre");

        lblSlot.setFont(new java.awt.Font("Cambria Math", 0, 16)); // NOI18N
        lblSlot.setText("lblSlot");

        jLabel20.setFont(new java.awt.Font("Cambria Math", 1, 16)); // NOI18N
        jLabel20.setText("Vaccine:");

        lblVaccine.setFont(new java.awt.Font("Cambria Math", 0, 16)); // NOI18N
        lblVaccine.setText("lblVaccine");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addGap(107, 107, 107)
                        .addComponent(lblName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 247, Short.MAX_VALUE)
                        .addComponent(jLabel23)
                        .addGap(37, 37, 37)
                        .addComponent(lblIC1)
                        .addGap(99, 99, 99)
                        .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(115, 115, 115))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblVacStatus)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(jLabel4)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel20))
                        .addGap(67, 67, 67)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblVaccine, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSlot, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(lblCentre, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCancelApp, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(106, 106, 106))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel7)
                .addGap(27, 27, 27)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(lblName)
                            .addComponent(lblIC1)
                            .addComponent(jLabel23))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(lblVacStatus))))
                .addGap(42, 42, 42)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel4)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(lblCentre)))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(btnCancelApp, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(lblSlot))
                .addGap(34, 34, 34)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(lblVaccine))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
            .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblClose2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblClose2MouseClicked
        PeopleMain pm = new PeopleMain();
        String name = lblName.getText();
        String ic = lblIC1.getText();
        String status = lblVacStatus.getText();
        pm.setVisible(true);
        pm.lblPeopleIC.setText(ic);
        pm.lblPeopleName.setText(name);
        pm.lblVacStatusM.setText(status);
        this.dispose();
        //        setVisible(false);
       
    }//GEN-LAST:event_lblClose2MouseClicked

    private void btnCancelAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelAppActionPerformed
        String ic = lblIC1.getText();
        String name = lblName.getText();
        if(a.findCitizen(ic, name)){
            String phoneno = a.getContactNo();
                String email = a.getEmail(); 
                String state = a.getState();
                String peopleType =a.getPeopleType();
            if (JOptionPane.showConfirmDialog(null, "Are you sure to cancel his/her appointment?", "WARNING",JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION ) {
                try{
                    FileWriter Writer = new FileWriter("Appointment/vaccineregistered.txt", true);
                    Writer.write(ic + ", " + name + ", " + phoneno + ", " + email + ", " + state + ", " + peopleType);
                    Writer.write(System.getProperty("line.separator"));
                    Writer.close();
                    JOptionPane.showMessageDialog(null, "Appointment Cancelled. Your status is changed back as 'Vaccination Registered'.");
                }catch(Exception e){
                    JOptionPane.showMessageDialog(null, "Error");
                }
                //Delete from old file
                a.removefromAddedApp(lblIC1);
                PeopleMain pm = new PeopleMain();
                String status = "Vaccination Registered";
                pm.setVisible(true);
                pm.lblPeopleIC.setText(ic);
                pm.lblPeopleName.setText(name);
                pm.lblVacStatusM.setText(status);
                this.setVisible(false);
                this.setDefaultCloseOperation(this.EXIT_ON_CLOSE);
                this.dispose();
            }
        }else if(a.findNonCitizen(ic, name)){
            String phoneno = a.getContactNo();
                String email = a.getEmail(); 
                String state = a.getState();
                String peopleType =a.getPeopleType();
            if (JOptionPane.showConfirmDialog(null, "Are you sure to cancel his/her appointment?", "WARNING",JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION ) {
                try{
                    FileWriter Writer = new FileWriter("Appointment/vaccineregistered.txt", true);
                    Writer.write(ic + ", " + name + ", " + phoneno + ", " + email + ", " + state + ", " + peopleType);
                    Writer.write(System.getProperty("line.separator"));
                    Writer.close();
                    JOptionPane.showMessageDialog(null, "Appointment Cancelled. Your status is changed back as 'Vaccination Registered'.");
                }catch(Exception e){
                    JOptionPane.showMessageDialog(null, "Error");
                }
                //Delete from old file
                a.removefromAddedApp(lblIC1);
                PeopleMain pm = new PeopleMain();
                String status = "Vaccination Registered";
                pm.setVisible(true);
                pm.lblPeopleIC.setText(ic);
                pm.lblPeopleName.setText(name);
                pm.lblVacStatusM.setText(status);
                this.setVisible(false);
                this.setDefaultCloseOperation(this.EXIT_ON_CLOSE);
                this.dispose();
            }
        }
    }//GEN-LAST:event_btnCancelAppActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        String ic = lblIC1.getText();
        String name = lblName.getText();

        if(a.findCitizen(ic, name)){
            try{
                FileWriter Writer = new FileWriter("Appointment/vaccineregistered.txt", true);
                String phoneno = a.getContactNo();
                String email = a.getEmail(); 
                String state = a.getState();
                String peopleType =a.getPeopleType();
                
                String filecontent = (ic + " : " + name + " : " + phoneno + " : " + email + " : " + state+ " : " + peopleType );
                Writer.write(filecontent);
                Writer.write(System.getProperty("line.separator"));
                Writer.close();
                JOptionPane.showMessageDialog(null, "Register Successful!");
                setVisible(false);
                PeopleMain hp = new PeopleMain();
                hp.setVisible(true);
                hp.lblPeopleIC.setText(ic);
                hp.lblPeopleName.setText(name);
                hp.lblVacStatusM.setText("Vaccination Registered");
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Error");
            }
        }else if(a.findNonCitizen(ic, name)){
            try{
                FileWriter Writer = new FileWriter("Appointment/vaccineregistered.txt", true);
                String phoneno = a.getContactNo();
                String email = a.getEmail(); 
                String state = a.getState();
                String peopleType =a.getPeopleType();
                
                String filecontent = (ic + " : " + name + " : " + phoneno + " : " + email + " : " + state + " : " + peopleType);
                Writer.write(filecontent);
                Writer.write(System.getProperty("line.separator"));
                Writer.close();
                JOptionPane.showMessageDialog(null, "Register Successful!");
                setVisible(false);
                PeopleMain hp = new PeopleMain();
                hp.setVisible(true);
                hp.lblPeopleIC.setText(ic);
                hp.lblPeopleName.setText(name);
                hp.lblVacStatusM.setText("Vaccination Registered");
            }catch(Exception ex){
                JOptionPane.showMessageDialog(null, "Error");
            }
        }
            

//        String state = cmbNewStateSlots.getSelectedItem().toString();
        //        String centre  = cmbNewStateCentre.getSelectedItem().toString();
        //        try {
            //            jTableSlot.setModel(new DefaultTableModel());
            //            as.viewSlotTable(cmbNewStateSlots, cmbNewStateCentre, jTableSlot);
            //            lblState.setText(state);
            //            lblCentre.setText(centre);
            //        } catch (IOException ex) {
            //            Logger.getLogger(PersonnelAddSlots.class.getName()).log(Level.SEVERE, null, ex);
            //        }
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void lblNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblNameKeyReleased

    
    }//GEN-LAST:event_lblNameKeyReleased

    private void lblIC1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblIC1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_lblIC1KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PeopleVaccineRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PeopleVaccineRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PeopleVaccineRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PeopleVaccineRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PeopleVaccineRegistration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCancelApp;
    public javax.swing.JButton btnRegister;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    public javax.swing.JLabel jLabel19;
    public javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JLabel lblCentre;
    private javax.swing.JLabel lblClose2;
    public javax.swing.JLabel lblIC1;
    public javax.swing.JLabel lblName;
    public javax.swing.JLabel lblSlot;
    public javax.swing.JLabel lblVacStatus;
    public javax.swing.JLabel lblVaccine;
    // End of variables declaration//GEN-END:variables
}
