/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VaccineRegistrationSystem;

import Classes.Centre;
import Classes.Vaccine;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Asus
 */
public class PersonnelManageVaccine extends javax.swing.JFrame {

    /**
     * Creates new form PersonnelManageVaccine
     */
    Centre c = new Centre();
    Vaccine v = new Vaccine();
    
    public PersonnelManageVaccine() {
        initComponents();
//       
//        try {
//            v.viewVaccineTable(lblCentre,lblState,jTableVacinneSupply);
//        } catch (IOException ex) {
//            Logger.getLogger(PersonnelManageVaccine.class.getName()).log(Level.SEVERE, null, ex);
//        }

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblClose = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        cmbNewState = new javax.swing.JComboBox<>();
        cmbNewCentre = new javax.swing.JComboBox<>();
        btnAdd = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        btnViewSlot1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        txtAssSearch = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableVacinneSupply = new javax.swing.JTable();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtVacName = new javax.swing.JTextField();
        txtVacCode = new javax.swing.JTextField();
        dateVacExpDate = new com.toedter.calendar.JDateChooser();
        txtVacQuantity = new javax.swing.JTextField();
        lblState = new javax.swing.JLabel();
        lblCentre = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));

        jLabel12.setFont(new java.awt.Font("Cambria Math", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Manage Vaccine Supply");

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/vaccine.png"))); // NOI18N
        jLabel13.setText("jLabel13");

        lblClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-close-window-30.png"))); // NOI18N
        lblClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addGap(398, 398, 398)
                .addComponent(lblClose)
                .addGap(35, 35, 35))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(lblClose))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12))))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(204, 204, 255));

        jLabel4.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        jLabel4.setText("Add New Vaccination Supply");

        jLabel5.setFont(new java.awt.Font("Cambria Math", 0, 16)); // NOI18N
        jLabel5.setText("Select State:");

        jLabel6.setFont(new java.awt.Font("Cambria Math", 0, 16)); // NOI18N
        jLabel6.setText("Select Centre:");

        jLabel14.setFont(new java.awt.Font("Cambria Math", 0, 16)); // NOI18N
        jLabel14.setText("Vaccine Name:");

        cmbNewState.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        cmbNewState.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "*None*", "Johor", "Kuala Lumpur", "Penang" }));
        cmbNewState.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbNewStateItemStateChanged(evt);
            }
        });
        cmbNewState.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbNewStateActionPerformed(evt);
            }
        });
        cmbNewState.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cmbNewStatePropertyChange(evt);
            }
        });

        cmbNewCentre.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        cmbNewCentre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "*None*" }));
        cmbNewCentre.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbNewCentreItemStateChanged(evt);
            }
        });
        cmbNewCentre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbNewCentreActionPerformed(evt);
            }
        });
        cmbNewCentre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cmbNewCentreKeyPressed(evt);
            }
        });

        btnAdd.setBackground(new java.awt.Color(255, 204, 153));
        btnAdd.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddMouseClicked(evt);
            }
        });
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnRemove.setBackground(new java.awt.Color(255, 204, 204));
        btnRemove.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        btnRemove.setText("Remove");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        btnViewSlot1.setBackground(new java.awt.Color(204, 255, 255));
        btnViewSlot1.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        btnViewSlot1.setText("View");
        btnViewSlot1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewSlot1ActionPerformed(evt);
            }
        });

        txtAssSearch.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        txtAssSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAssSearchKeyReleased(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Cambria Math", 0, 16)); // NOI18N
        jLabel18.setText("Search:");

        jTableVacinneSupply.setFont(new java.awt.Font("Cambria Math", 0, 16)); // NOI18N
        jTableVacinneSupply.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableVacinneSupply.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableVacinneSupplyMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableVacinneSupply);

        jLabel19.setFont(new java.awt.Font("Cambria Math", 0, 16)); // NOI18N
        jLabel19.setText("Vaccine Code:");

        jLabel20.setFont(new java.awt.Font("Cambria Math", 0, 16)); // NOI18N
        jLabel20.setText("Expiry Date:");

        jLabel21.setFont(new java.awt.Font("Cambria Math", 0, 16)); // NOI18N
        jLabel21.setText("Quantity: ");

        txtVacName.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        txtVacName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVacNameActionPerformed(evt);
            }
        });

        txtVacCode.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        txtVacCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVacCodeActionPerformed(evt);
            }
        });

        txtVacQuantity.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        txtVacQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVacQuantityActionPerformed(evt);
            }
        });
        txtVacQuantity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtVacQuantityKeyTyped(evt);
            }
        });

        lblState.setFont(new java.awt.Font("Cambria Math", 0, 16)); // NOI18N
        lblState.setText(" ");

        lblCentre.setFont(new java.awt.Font("Cambria Math", 0, 16)); // NOI18N
        lblCentre.setText("lblCentre");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1014, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(18, 18, 18)
                                .addComponent(txtAssSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                                        .addComponent(jLabel19)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtVacCode, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtVacName, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(68, 68, 68)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel21))
                                .addGap(44, 44, 44)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(dateVacExpDate, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                                    .addComponent(txtVacQuantity))
                                .addGap(78, 78, 78)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnRemove, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)))))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(33, 33, 33)
                                .addComponent(lblState))
                            .addComponent(cmbNewState, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(81, 81, 81)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(cmbNewCentre, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(116, 116, 116)
                                .addComponent(btnViewSlot1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(37, 37, 37)
                                .addComponent(lblCentre))))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 1085, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(lblState))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbNewState, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(lblCentre))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbNewCentre, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnViewSlot1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(29, 29, 29)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtAssSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jLabel20)
                            .addComponent(txtVacName, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(dateVacExpDate, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel21)
                    .addComponent(txtVacCode, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVacQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(281, 281, 281))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
        PersonnelMain home = new PersonnelMain();
        home.setVisible(true);
        this.setVisible(false);
        this.setDefaultCloseOperation(this.EXIT_ON_CLOSE);
        this.dispose();
        //        setVisible(false);
    }//GEN-LAST:event_lblCloseMouseClicked

    private void cmbNewStateItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbNewStateItemStateChanged
        String state = cmbNewState.getSelectedItem().toString();
        
        if (state.equals("Johor")) {
            try {
                cmbNewCentre.removeAllItems();
                c.fillComboBoxJohor(cmbNewCentre);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Now, select the centre.!");
            }
        } else if (state.equals("Kuala Lumpur")) {
            try {
                cmbNewCentre.removeAllItems();
                c.fillComboBoxKL(cmbNewCentre);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Now, select the centre.!");
            }
        } else if (state.equals("Penang")) {
            try {
                cmbNewCentre.removeAllItems();
                c.fillComboBoxPenang(cmbNewCentre);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Now, select the centre.!");
            }
        }
    }//GEN-LAST:event_cmbNewStateItemStateChanged

    private void cmbNewStateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbNewStateActionPerformed
        String state = cmbNewState.getSelectedItem().toString();
        if(state.equals("*None*")){
            JOptionPane.showMessageDialog(null, "Please select the state.");
            cmbNewCentre.removeAllItems();
        }

    }//GEN-LAST:event_cmbNewStateActionPerformed

    private void cmbNewStatePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cmbNewStatePropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbNewStatePropertyChange

    private void cmbNewCentreItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbNewCentreItemStateChanged

    }//GEN-LAST:event_cmbNewCentreItemStateChanged

    private void cmbNewCentreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbNewCentreActionPerformed

    }//GEN-LAST:event_cmbNewCentreActionPerformed

    private void cmbNewCentreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmbNewCentreKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbNewCentreKeyPressed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
       String vacname = txtVacName.getText();
        String vaccode = txtVacCode.getText();
        Date expdate = dateVacExpDate.getDate();
        int quantity = Integer.parseInt(txtVacQuantity.getText());
        String labelcentre = lblCentre.getText();
        String labelstate = lblState.getText(); 
        
        if("*None*".equals(cmbNewState.getSelectedItem().toString())){
            JOptionPane.showMessageDialog(null, "Please select the state.");
        }else if("*None*".equals(cmbNewCentre.getSelectedItem().toString())){
            JOptionPane.showMessageDialog(null, "Please select the centre.");
        }else if(labelstate.equals(" ") && labelcentre.equals(" ") ){
            JOptionPane.showMessageDialog(null, "Please click the 'VIEW' button to proceed.");
        }else if(!labelcentre.equals(cmbNewCentre.getSelectedItem().toString())){
            JOptionPane.showMessageDialog(null, "Please click the 'VIEW' button to proceed.");
        }else if(!labelstate.equals(cmbNewState.getSelectedItem().toString())){
            JOptionPane.showMessageDialog(null, "Please click the 'VIEW' button to proceed.");
        }else if(vacname.equals("")){
            JOptionPane.showMessageDialog(null, "Please enter the Vaccine Name.");
        }else if(vaccode.equals("")){
            JOptionPane.showMessageDialog(null, "Please enter the Vaccine Code.");
        }else if(expdate == null){
            JOptionPane.showMessageDialog(null, "Please select the Expiry Date.");
        }else if(txtVacQuantity.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please enter the quantity.");
        }else{
            v.addVacSupply(labelstate, labelcentre, vacname, vaccode, dateVacExpDate, quantity); 
            try {
                jTableVacinneSupply.setModel(new DefaultTableModel());
                v.viewVaccineTable(lblState, lblCentre, jTableVacinneSupply);
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(null, "Error");
            }
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
String state = lblState.getText();
        String centre = lblCentre.getText();
        String vacname = txtVacName.getText();
        String vaccode = txtVacCode.getText();
        Date expdate = dateVacExpDate.getDate();
//        int quantity = Integer.parseInt(txtVacQuantity.getText());
        
        if("*None*".equals(cmbNewState.getSelectedItem().toString())){
            JOptionPane.showMessageDialog(null, "Please select the state.");
        }else if("*None*".equals(cmbNewCentre.getSelectedItem().toString())){
            JOptionPane.showMessageDialog(null, "Please select the centre.");
        }else if(state.equals(" ") && centre.equals(" ") ){
            JOptionPane.showMessageDialog(null, "Please click the 'VIEW' button to proceed.");
        }else if(!centre.equals(cmbNewCentre.getSelectedItem().toString())){
            JOptionPane.showMessageDialog(null, "Please click the 'VIEW' button to proceed.");
        }else if(!state.equals(cmbNewState.getSelectedItem().toString())){
            JOptionPane.showMessageDialog(null, "Please click the 'VIEW' button to proceed.");
        }else if(vacname.equals("")){
            JOptionPane.showMessageDialog(null, "Please enter the Vaccine Name.");
        }else if(vaccode.equals("")){
            JOptionPane.showMessageDialog(null, "Please enter the Vaccine Code.");
        }else if(expdate == null){
            JOptionPane.showMessageDialog(null, "Please select the Expiry Date.");
        }else if(txtVacQuantity.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please enter the quantity.");
        }else{
            v.deleteVacSupply(state, centre, txtVacName, txtVacCode, dateVacExpDate, txtVacQuantity);
            jTableVacinneSupply.setModel(new DefaultTableModel());
            try {
                v.viewVaccineTable(lblState, lblCentre, jTableVacinneSupply);
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(null, "Error");
            }
        }
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnViewSlot1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewSlot1ActionPerformed
        String state = cmbNewState.getSelectedItem().toString();
        String centre = cmbNewCentre.getSelectedItem().toString();

        if ("*None*".equals(cmbNewState.getSelectedItem().toString())) {
            JOptionPane.showMessageDialog(null, "Please select the state.");
        } else if ("*None*".equals(cmbNewCentre.getSelectedItem().toString())) {
            JOptionPane.showMessageDialog(null, "Please select the centre.");
        } else {
//            panel.setVisible(true);
            lblState.setText(state);
            lblCentre.setText(centre);
            try {
                jTableVacinneSupply.setModel(new DefaultTableModel());
                v.viewVaccineTable(lblState, lblCentre, jTableVacinneSupply);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Error.");
            }
        }
    }//GEN-LAST:event_btnViewSlot1ActionPerformed

    private void txtAssSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAssSearchKeyReleased
        DefaultTableModel table = (DefaultTableModel) jTableVacinneSupply.getModel();
        String search = txtAssSearch.getText();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(table);
        jTableVacinneSupply.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(search));
    }//GEN-LAST:event_txtAssSearchKeyReleased

    private void jTableVacinneSupplyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableVacinneSupplyMouseClicked
        DefaultTableModel tblModel = (DefaultTableModel) jTableVacinneSupply.getModel();
        String vaccinename = tblModel.getValueAt(jTableVacinneSupply.getSelectedRow(), 0).toString();
        String vaccinecode = tblModel.getValueAt(jTableVacinneSupply.getSelectedRow(), 1).toString();
        String expirydate = tblModel.getValueAt(jTableVacinneSupply.getSelectedRow(), 2).toString();
        String quantity = tblModel.getValueAt(jTableVacinneSupply.getSelectedRow(), 3).toString();
        try {
            java.util.Date thedate = new SimpleDateFormat("yyyy-MM-dd").parse(expirydate);
            dateVacExpDate.setDate(thedate);
            txtVacName.setText(vaccinename);
            txtVacCode.setText(vaccinecode);
            txtVacQuantity.setText(quantity);
        } catch (ParseException ex) {
            java.util.logging.Logger.getLogger(PersonnelManageVaccine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTableVacinneSupplyMouseClicked

    private void txtVacNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVacNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVacNameActionPerformed

    private void txtVacCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVacCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVacCodeActionPerformed

    private void txtVacQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVacQuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVacQuantityActionPerformed

    private void txtVacQuantityKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtVacQuantityKeyTyped
         char ch = evt.getKeyChar();

        if(!Character.isDigit(ch)){
            evt.consume();
        }
    }//GEN-LAST:event_txtVacQuantityKeyTyped

    private void btnAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PersonnelManageVaccine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PersonnelManageVaccine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PersonnelManageVaccine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PersonnelManageVaccine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PersonnelManageVaccine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnViewSlot1;
    private javax.swing.JComboBox<String> cmbNewCentre;
    private javax.swing.JComboBox<String> cmbNewState;
    private com.toedter.calendar.JDateChooser dateVacExpDate;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTableVacinneSupply;
    private javax.swing.JLabel lblCentre;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblState;
    private javax.swing.JTextField txtAssSearch;
    private javax.swing.JTextField txtVacCode;
    private javax.swing.JTextField txtVacName;
    private javax.swing.JTextField txtVacQuantity;
    // End of variables declaration//GEN-END:variables
}
