/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VaccineRegistrationSystem;

import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class PersonnelMain extends javax.swing.JFrame {

    /**
     * Creates new form LibrarianSite
     */
    public PersonnelMain() {
        initComponents();
//        setLocationRelativeTo(null);
    }
    
    
    void username(String user){
         lblUser.setText(user);
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblBackground = new javax.swing.JLabel();
        lbl = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmiAddpersonnel = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jmiViewPersonnel = new javax.swing.JMenuItem();
        jMenuPeople = new javax.swing.JMenu();
        jmiAddPeople = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jmiViewPeople = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jmiAddCentre = new javax.swing.JMenu();
        jmiAddslot = new javax.swing.JMenu();
        jApp = new javax.swing.JMenu();
        jmiAssignApp = new javax.swing.JMenuItem();
        jmilManageApp = new javax.swing.JMenuItem();
        jmilManageCompletion = new javax.swing.JMenuItem();
        jmilAppCompleted = new javax.swing.JMenuItem();
        jVaciine = new javax.swing.JMenu();
        jmiManageVaccine = new javax.swing.JMenuItem();
        jmiStatistics = new javax.swing.JMenu();
        jmiSummaryReport = new javax.swing.JMenuItem();
        jPeopleProfile = new javax.swing.JMenu();
        jMenuLogOut = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add Librarian");
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/mainpage.png"))); // NOI18N

        lbl.setFont(new java.awt.Font("Segoe Print", 0, 36)); // NOI18N

        lblUser.setFont(new java.awt.Font("Monotype Corsiva", 0, 48)); // NOI18N
        lblUser.setText("  ");

        jLabel5.setFont(new java.awt.Font("Cambria Math", 0, 24)); // NOI18N
        jLabel5.setText("WELCOME ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(lblBackground, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(lbl)
                        .addContainerGap(646, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUser)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(jLabel5)
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblUser)
                    .addComponent(lbl))
                .addContainerGap(391, Short.MAX_VALUE))
            .addComponent(lblBackground, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
        );

        jMenuBar1.setBackground(new java.awt.Color(153, 102, 255));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jMenuBar1.setForeground(new java.awt.Color(153, 102, 255));
        jMenuBar1.setFont(new java.awt.Font("Cambria Math", 0, 18)); // NOI18N

        jMenu1.setBackground(new java.awt.Color(153, 102, 255));
        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Adminpic.png"))); // NOI18N
        jMenu1.setText("Personnel");
        jMenu1.setFont(new java.awt.Font("Cambria Math", 0, 24)); // NOI18N

        jmiAddpersonnel.setFont(new java.awt.Font("Cambria Math", 0, 24)); // NOI18N
        jmiAddpersonnel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/AddUser.png"))); // NOI18N
        jmiAddpersonnel.setText("Add Personnel");
        jmiAddpersonnel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAddpersonnelActionPerformed(evt);
            }
        });
        jMenu1.add(jmiAddpersonnel);
        jMenu1.add(jSeparator1);

        jmiViewPersonnel.setFont(new java.awt.Font("Cambria Math", 0, 24)); // NOI18N
        jmiViewPersonnel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/SearchUser.png"))); // NOI18N
        jmiViewPersonnel.setText("View Personnel");
        jmiViewPersonnel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiViewPersonnelActionPerformed(evt);
            }
        });
        jMenu1.add(jmiViewPersonnel);

        jMenuBar1.add(jMenu1);

        jMenuPeople.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/profile.png"))); // NOI18N
        jMenuPeople.setText("People");
        jMenuPeople.setFont(new java.awt.Font("Cambria Math", 0, 24)); // NOI18N

        jmiAddPeople.setFont(new java.awt.Font("Cambria Math", 0, 24)); // NOI18N
        jmiAddPeople.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/AddUser.png"))); // NOI18N
        jmiAddPeople.setText("Add People");
        jmiAddPeople.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAddPeopleActionPerformed(evt);
            }
        });
        jMenuPeople.add(jmiAddPeople);
        jMenuPeople.add(jSeparator3);

        jmiViewPeople.setFont(new java.awt.Font("Cambria Math", 0, 24)); // NOI18N
        jmiViewPeople.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/SearchUser.png"))); // NOI18N
        jmiViewPeople.setText("View People");
        jmiViewPeople.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiViewPeopleActionPerformed(evt);
            }
        });
        jMenuPeople.add(jmiViewPeople);

        jMenuBar1.add(jMenuPeople);

        jMenu8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Centre_1.png"))); // NOI18N
        jMenu8.setText("Centre & Slot");
        jMenu8.setFont(new java.awt.Font("Cambria Math", 0, 24)); // NOI18N

        jmiAddCentre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/cslot.png"))); // NOI18N
        jmiAddCentre.setText("Add New Centre");
        jmiAddCentre.setFont(new java.awt.Font("Cambria Math", 0, 24)); // NOI18N
        jmiAddCentre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmiAddCentreMouseClicked(evt);
            }
        });
        jmiAddCentre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAddCentreActionPerformed(evt);
            }
        });
        jMenu8.add(jmiAddCentre);

        jmiAddslot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/centreslot.png"))); // NOI18N
        jmiAddslot.setText("Add New Slot");
        jmiAddslot.setFont(new java.awt.Font("Cambria Math", 0, 24)); // NOI18N
        jmiAddslot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmiAddslotMouseClicked(evt);
            }
        });
        jmiAddslot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAddslotActionPerformed(evt);
            }
        });
        jMenu8.add(jmiAddslot);

        jMenuBar1.add(jMenu8);

        jApp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/addappointment.png"))); // NOI18N
        jApp.setText("Appointment");
        jApp.setFont(new java.awt.Font("Cambria Math", 0, 24)); // NOI18N
        jApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAppActionPerformed(evt);
            }
        });

        jmiAssignApp.setFont(new java.awt.Font("Cambria Math", 0, 24)); // NOI18N
        jmiAssignApp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/appointment.png"))); // NOI18N
        jmiAssignApp.setText("Assign Appointment");
        jmiAssignApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAssignAppActionPerformed(evt);
            }
        });
        jApp.add(jmiAssignApp);

        jmilManageApp.setFont(new java.awt.Font("Cambria Math", 0, 24)); // NOI18N
        jmilManageApp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/bookmark.png"))); // NOI18N
        jmilManageApp.setText("Manage Appointment");
        jmilManageApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmilManageAppActionPerformed(evt);
            }
        });
        jApp.add(jmilManageApp);

        jmilManageCompletion.setFont(new java.awt.Font("Cambria Math", 0, 24)); // NOI18N
        jmilManageCompletion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/managevaccine.png"))); // NOI18N
        jmilManageCompletion.setText("Vaccination Completion");
        jmilManageCompletion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmilManageCompletionActionPerformed(evt);
            }
        });
        jApp.add(jmilManageCompletion);

        jmilAppCompleted.setFont(new java.awt.Font("Cambria Math", 0, 24)); // NOI18N
        jmilAppCompleted.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/vaccinated.png"))); // NOI18N
        jmilAppCompleted.setText("Completed Vaccination");
        jmilAppCompleted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmilAppCompletedActionPerformed(evt);
            }
        });
        jApp.add(jmilAppCompleted);

        jMenuBar1.add(jApp);

        jVaciine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/vaccine.png"))); // NOI18N
        jVaciine.setText("Vaccine");
        jVaciine.setFont(new java.awt.Font("Cambria Math", 0, 24)); // NOI18N

        jmiManageVaccine.setFont(new java.awt.Font("Cambria Math", 0, 24)); // NOI18N
        jmiManageVaccine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Centre.png"))); // NOI18N
        jmiManageVaccine.setText("Manage Vaccine");
        jmiManageVaccine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiManageVaccineActionPerformed(evt);
            }
        });
        jVaciine.add(jmiManageVaccine);

        jMenuBar1.add(jVaciine);

        jmiStatistics.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Statistics.png"))); // NOI18N
        jmiStatistics.setText("Statistics ");
        jmiStatistics.setFont(new java.awt.Font("Cambria Math", 0, 24)); // NOI18N
        jmiStatistics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiStatisticsActionPerformed(evt);
            }
        });

        jmiSummaryReport.setFont(new java.awt.Font("Cambria Math", 0, 24)); // NOI18N
        jmiSummaryReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Centre.png"))); // NOI18N
        jmiSummaryReport.setText("Summary Report");
        jmiSummaryReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSummaryReportActionPerformed(evt);
            }
        });
        jmiStatistics.add(jmiSummaryReport);

        jMenuBar1.add(jmiStatistics);

        jPeopleProfile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/SearchUser.png"))); // NOI18N
        jPeopleProfile.setText("Profile");
        jPeopleProfile.setFont(new java.awt.Font("Cambria Math", 0, 24)); // NOI18N
        jPeopleProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPeopleProfileMouseClicked(evt);
            }
        });
        jPeopleProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPeopleProfileActionPerformed(evt);
            }
        });
        jMenuBar1.add(jPeopleProfile);

        jMenuLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Logout.png"))); // NOI18N
        jMenuLogOut.setText("LogOut");
        jMenuLogOut.setFont(new java.awt.Font("Cambria Math", 0, 24)); // NOI18N
        jMenuLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuLogOutMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuLogOut);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jmiViewPersonnelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiViewPersonnelActionPerformed
        new ViewPersonnel().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jmiViewPersonnelActionPerformed

    private void jmiViewPeopleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiViewPeopleActionPerformed
        new ViewPeople().setVisible(true);
        new PersonnelAddCentre().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jmiViewPeopleActionPerformed

    private void jMenuLogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuLogOutMouseClicked
        int a = JOptionPane.showConfirmDialog(null, "Do you really want to Log Out?","Select",JOptionPane.YES_NO_OPTION);
        if(a==0){
           setVisible(false);
            new MainPage().setVisible(true);  
        }
        
    }//GEN-LAST:event_jMenuLogOutMouseClicked

    private void jmiManageVaccineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiManageVaccineActionPerformed
        this.dispose();
        new PersonnelManageVaccine().setVisible(true);
    }//GEN-LAST:event_jmiManageVaccineActionPerformed

    private void jmiAssignAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAssignAppActionPerformed
        this.dispose();
        new PersonnelAssignAppointment().setVisible(true);
    }//GEN-LAST:event_jmiAssignAppActionPerformed

    private void jmiStatisticsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiStatisticsActionPerformed
        
    }//GEN-LAST:event_jmiStatisticsActionPerformed

    private void jPeopleProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPeopleProfileMouseClicked
        // TODO add your handling code here:
        new PersonnelProfile().setVisible(true);
    }//GEN-LAST:event_jPeopleProfileMouseClicked

    private void jPeopleProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPeopleProfileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPeopleProfileActionPerformed

    private void jmilManageAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmilManageAppActionPerformed
        new PersonnelManageAppointment().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jmilManageAppActionPerformed

    private void jmiAddCentreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAddCentreActionPerformed

    }//GEN-LAST:event_jmiAddCentreActionPerformed

    private void jmiAddCentreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmiAddCentreMouseClicked
        new PersonnelAddCentre().setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jmiAddCentreMouseClicked

    private void jmiAddslotMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmiAddslotMouseClicked
    new PersonnelAddSlots().setVisible(true);
        this.dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_jmiAddslotMouseClicked

    private void jmiAddslotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAddslotActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmiAddslotActionPerformed

    private void jmiSummaryReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSummaryReportActionPerformed
        //new PrintReport().setVisible(true);
        //this.dispose();
    }//GEN-LAST:event_jmiSummaryReportActionPerformed

    private void jmiAddpersonnelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAddpersonnelActionPerformed
        new RegisterPersonnel().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jmiAddpersonnelActionPerformed

    private void jAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAppActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jAppActionPerformed

    private void jmiAddPeopleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAddPeopleActionPerformed
        new RegisterPeople().setVisible(true);
//        this.dispose();
    }//GEN-LAST:event_jmiAddPeopleActionPerformed

    private void jmilManageCompletionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmilManageCompletionActionPerformed
        new PersonnelAppointmentCompletion().setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jmilManageCompletionActionPerformed

    private void jmilAppCompletedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmilAppCompletedActionPerformed
        this.dispose();
        new PersonnelCompletedAppointment().setVisible(true);
    }//GEN-LAST:event_jmilAppCompletedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PersonnelMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PersonnelMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PersonnelMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PersonnelMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PersonnelMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jApp;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuLogOut;
    private javax.swing.JMenu jMenuPeople;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu jPeopleProfile;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JMenu jVaciine;
    private javax.swing.JMenu jmiAddCentre;
    private javax.swing.JMenuItem jmiAddPeople;
    private javax.swing.JMenuItem jmiAddpersonnel;
    private javax.swing.JMenu jmiAddslot;
    private javax.swing.JMenuItem jmiAssignApp;
    private javax.swing.JMenuItem jmiManageVaccine;
    private javax.swing.JMenu jmiStatistics;
    private javax.swing.JMenuItem jmiSummaryReport;
    private javax.swing.JMenuItem jmiViewPeople;
    private javax.swing.JMenuItem jmiViewPersonnel;
    private javax.swing.JMenuItem jmilAppCompleted;
    private javax.swing.JMenuItem jmilManageApp;
    private javax.swing.JMenuItem jmilManageCompletion;
    private javax.swing.JLabel lbl;
    private javax.swing.JLabel lblBackground;
    public javax.swing.JLabel lblUser;
    // End of variables declaration//GEN-END:variables
}
